name: Refractor
version: 1.5.6
main: company.fourleafclover.Refractor.Refractor
author: Keturah#5275
api-version: 1.17
commands:
  generror:
    description: Generate a man-made execption
    usage: /<command>
    aliases:



