name: Refractor
version: 1.7.2
main: company.fourleafclover.Refractor.Refractor
author: Keturah#5275
api-version: 1.17
commands:
  generror:
    description: Generate a man-made execption
    usage: /<command
    aliases: create-error
  dsc:
    description: Send the link to our discord!
    usage: /<command
    aliases: discord
  feed:
    description: Feeds the player
    usage: /<command
    aliases: feedme
  heal:
    description: Heals the player
    usage: /<command
    aliases: healme








