name: Refractor
version: 1.8
main: company.fourleafclover.Refractor.Refractor
author: Keturah#5275
api-version: 1.17
commands:
  generror:
    description: Generate a man-made execption
    usage: /<command>
    aliases: create-error
  dsc:
    description: Send the link to our discord!
    usage: /<command>
    aliases: discord
  feed:
    description: Feeds the player
    usage: /<command>
    aliases: feedme
  heal:
    description: Heals the player
    usage: /<command>
    aliases: healme
  notify:
    description: Send a desktop toast
    usage: /<command>
  day:
    description: Set time to day
    usage: /<command>
  night:
    description: Set time to night
    usage: /<command>
  gmc:
    description: Set gamemode to creative
    usage: /<command>
  gms:
    description: Set gamemode to survival
    usage: /<command>
  gma:
    description: Set gamemode to adventure
    usage: /<command>
  gmsp:
    description: Set gamemode to spectator
    usage: /<command>
  dadjoke:
    description: Sends a random dad joke
    usage: /<command>
  getinfo:
    description: Sends information about a player
    usage: /<command>










