name: Refractor
version: 1.7.1
main: company.fourleafclover.Refractor.Refractor
author: Keturah#5275
api-version: 1.17
commands:
  generror:
    description: Generate a man-made execption
    usage: /generror
    aliases: errorgenerate
  dsc:
    description: Send the link to our discord!
    usage: /dsc
    aliases: discord
  feed:
    description: Feeds the player
    usage: /feed
    aliases: feedme






