name: Refractor
version: 1.8.1
main: company.fourleafclover.Refractor.Refractor
author: Keturah#5275
api-version: 1.17
commands:
  generror:
    description: Generate a man-made execption
    usage: /<command>
    aliases: create-error
  dsc:
    description: Send the link to our discord!
    usage: /<command>
    permission: refractor.dsc
    aliases: discord
  feed:
    description: Feeds the player
    usage: /<command>
    permission: refractor.feed
    aliases: feedme
  heal:
    description: Heals the player
    usage: /<command>
    permission: refractor.heal
    aliases: healme
  day:
    description: Set time to day
    usage: /<command>
    permission: refractor.day
  night:
    description: Set time to night
    usage: /<command>
    permission: refractor.day
  gmc:
    description: Set gamemode to creative
    usage: /<command>
    permission: refractor.gmc
  gms:
    description: Set gamemode to survival
    usage: /<command>
    permission: refractor.gms
  gma:
    description: Set gamemode to adventure
    usage: /<command>
    permission: refractor.gma
  gmsp:
    description: Set gamemode to spectator
    usage: /<command>
    permission: refractor.gmsp
  dadjoke:
    description: Sends a random dad joke
    usage: /<command>
    permission: refractor.dadjoke
  getinfo:
    description: Sends information about a player
    usage: /<command>
    permission: refractor.getinfo










