name: Refractor
version: 4.2
main: xyz.necrozma.Refractor.Main
author: Necrozma
api-version: '1.20'
description: Just some server essentials
website: necrozma.xyz
depend: [PlaceholderAPI, ProtocolLib]
commands:
  generror:
    description: Manually create execption
    usage: /<command>
    aliases: create-error
  dsc:
    description: Send the link to our discord!
    usage: /<command>
    permission: refractor.dsc
    aliases: discord
  feed:
    description: Feeds the player
    usage: /<command>
    permission: refractor.feed
    aliases: feedme
  heal:
    description: Heals the player
    usage: /<command>
    permission: refractor.heal
    aliases: healme
  day:
    description: Set time to day
    usage: /<command>
    permission: refractor.day
  night:
    description: Set time to night
    usage: /<command>
    permission: refractor.night
  gmc:
    description: Set gamemode to creative
    usage: /<command>
    permission: refractor.gmc
  gms:
    description: Set gamemode to survival
    usage: /<command>
    permission: refractor.gms
  gma:
    description: Set gamemode to adventure
    usage: /<command>
    permission: refractor.gma
  gmsp:
    description: Set gamemode to spectator
    usage: /<command>
    permission: refractor.gmsp
  dadjoke:
    description: Sends a random dad joke
    usage: /<command>
    permission: refractor.dadjoke
  getinfo:
    description: Gets information about a player
    usage: /<command>
    permission: refractor.getinfo
  refractor:
    description: Plugin information
    usage: /<command>
  title:
    description: Sends a title to a player
    usage: /<command>
    permission: refractor.title
  give:
    description: Give a player an item
    usage: /<command>
    permission: refractor.give
  ban:
    description: Ban a player
    usage: /<command>
    permission: refractor.ban
  unban:
    description: Unban a player
    usage: /<command>
    permission: refractor.unban
  mute:
    description: Mute a player
    usage: /<command>
    permission: refractor.mute
  unmute:
    description: Unute a player
    usage: /<command>
    permission: refractor.unmute















