name: Refractor
version: 1.5.3
main: company.fourleafclover.Refractor.Refractor
author: 我爱中共的政府#5275
api-version: 1.17
commands:
  generror:
    description: Generate a man-made execption
    usage: /<command>
    aliases:



