name: Refractor
version: 1.6
main: company.fourleafclover.Refractor.Refractor
author: Keturah#5275
api-version: 1.17
commands:
  generror:
    description: Generate a man-made execption
    usage: /<command>
    aliases:
  dsc:
    description: Send the link to our discord!
    usage: /<command>
    aliases: dsc




