package company.fourleafclover.Refractor;

import java.lang.Exception;
import io.sentry.Sentry;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

public class commands implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (!(sender instanceof Player)) { return true; }
        Player player = (Player) sender;

        //generate execution
        if(cmd.getName().equalsIgnoreCase("generror")) {
            try {
                throw new Exception("This is a test exception generated by" + sender.getName());
            } catch (Exception e) {
                Sentry.captureException(e);
            }
        }


        return true;
    }


}
